Course For NLP from LinkedIn

Heavenly Father is guiding me - this one has a text classification project.

https://www.linkedin.com/learning/natural-language-processing-with-pytorch/popular-topics-in-nlp

The teacher is Zhonyu Pan, Content Creator at LinkedIn

We'll be using PyTorch, and we'll use a Convolutional Neural Network (feature rather than position) to do our text classification.

`Input -> Convolution -> Pooling -> ... -> Fully-connected layer -> Output`

We are also learning about RNNs. RNN doesn't only pass data forward, but only feeds the data back into itself. CNN only goes forward. RNN can remember context before and after words in a sequence. It's usually slower that a CNN.

It's time to learn PyTorch

<b>PyTorch tensor</b>

A tensor is a data structure or data container we use in PyTorch for carrying arrays of numbers.

<b>a. Creating a tensor</b>

In [1]:
# prompt: use pip to install PyTorch

#!pip install torch torchvision
!pip install torch


  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21

In [2]:
# prompt: import pytorch as well as numpy

import torch
import numpy as np


In [6]:
#  prompt: Construct a tensor named tensor0 from the array,
#+ array = [[1, 2], [7, 4],[5, 6]].
#+ Print the tensor.
#+ Output "The data structure type of tensor0: ",
#+ then appropriately continue the statement using code.
#+ After, output "The data type of tensor0: " and continue
#+ the statement appropriately using code.

#import torch

# Create a tensor named tensor0 from the array
array = [[1, 2], [7, 4], [5, 6]]
tensor0 = torch.tensor(array)

## Added by DWB
print(tensor0)

# Print the tensor
print("The data structure type of tensor0: ", type(tensor0))

# Print the data type of tensor0
print("The data type of tensor0: ", tensor0.dtype)


tensor([[1, 2],
        [7, 4],
        [5, 6]])
The data structure type of tensor0:  <class 'torch.Tensor'>
The data type of tensor0:  torch.int64


In [7]:
#  prompt: Now, create a tensor named tensor0 from the same data,
#+ but as a numpy array. Continue the other steps as before.

#import torch
#import numpy as np

# Create a tensor named tensor0 from the array as a numpy array
array = np.array([[1, 2], [7, 4], [5, 6]])
tensor1 = torch.tensor(array)

## Added by DWB
print(tensor1)

# Print the tensor
print("The data structure type of tensor1: ", type(tensor1))

# Print the data type of tensor1
print("The data type of tensor1: ", tensor1.dtype)


tensor([[1, 2],
        [7, 4],
        [5, 6]])
The data structure type of tensor1:  <class 'torch.Tensor'>
The data type of tensor1:  torch.int64


<b>b. Common Methods: Slicing and Concatenation</b>

_Slicing_

In [14]:
# prompt: Create tensorA = tensor([[1.,1.,1.],[2.,2.,2.]])
# so that the two rows of tensorA are different.
# and... create tensorB = tensor([[3.,3.,3.],[4.,4.,4.]])
# so that the two rows of tensorB are different
# using only PyTorch methods.
# Print the contents of the two tensors.

#import torch

# Create tensorA with two different rows
tensorA = torch.cat((torch.ones(1, 3), 2 * torch.ones(1, 3)), dim=0)

# Create tensorB with two different rows
tensorB = torch.cat((3 * torch.ones(1, 3), 4 * torch.ones(1, 3)), dim=0)

# Print the contents of the two tensors
print("tensorA:", tensorA)
print("tensorB:", tensorB)


tensorA: tensor([[1., 1., 1.],
        [2., 2., 2.]])
tensorB: tensor([[3., 3., 3.],
        [4., 4., 4.]])


In [ ]:
# prompt: Impressive, but you can pass in '[[1.,1.,1.],[2.,2.,2.]]' for tensorA
# and '[[3.,3.,3.],[4.,4.,4.]]' for tensorB.

## Create tensorA with two different rows
#tensorA = torch.cat((torch.ones(1, 3), 2 * torch.ones(1, 3)), dim=0)
#
## Create tensorB with two different rows
#tensorB = torch.cat((3 * torch.ones(1, 3), 4 * torch.ones(1, 3)), dim=0)
#
## Print the contents of the two tensors
#print("tensorA:", tensorA)
#print("tensorB:", tensorB)

# Pass in '[[1.,1.,1.],[2.,2.,2.]]' for tensorA
# and '[[3.,3.,3.],[4.,4.,4.]]' for tensorB
tensorA = torch.tensor([[1.,1.,1.],[2.,2.,2.]])
tensorB = torch.tensor([[3.,3.,3.],[4.,4.,4.]])

# Print the contents of the two tensors
print("tensorA:", tensorA)
print("tensorB:", tensorB)


In [16]:
# prompt: Output
# "Slicing the first two rows of tensorA" + \
# "(index one inclusive, index two exclusive)",
# then write the code to do so and print the result
# Follow the same procedure with the text,
# "Slicing the first two columns of tensorA" + \
# "(take all rows, then slice columns)".

# Slicing the first two rows of tensorA (index one inclusive, index two exclusive)
print("Slicing the first two rows of tensorA (index one inclusive, index two exclusive):")
print(tensorA[1:2, :])

# Slicing the first two columns of tensorA (take all rows, then slice columns)
print("Slicing the first two columns of tensorA (take all rows, then slice columns):")
print(tensorA[:, :2])


Slicing the first two rows of tensorA (index one inclusive index two exclusive):
tensor([[1., 1., 1.],
        [2., 2., 2.]])
Slicing the first two columns of tensorA (take all rows, then slice columns):
tensor([[1., 1.],
        [2., 2.]])


Her code

In [17]:
# Slicing is all the same as numpy arrays
print('Slicing the first two rows of tensorA (index one inclusive index two exclusive): ')
print(tensorA[:2])
print("Slicing the first two columns of tensorA (take all rows, then slice columns):")
print(tensorA[:, :2])

Slicing the first two rows of tensorA (index one inclusive index two exclusive): 
tensor([[1., 1., 1.],
        [2., 2., 2.]])
Slicing the first two columns of tensorA (take all rows, then slice columns):
tensor([[1., 1.],
        [2., 2.]])


_Concatenation_

In [19]:
# prompt: Output
# "Vertically concatenate tensorA and tensorB: (default: dim=0)"
# then do so, using the variable concat_v. Then, print the variable.

## It did too much again : )
#import torch
#
## Create tensorA with two different rows
#tensorA = torch.tensor([[1.,1.,1.],[2.,2.,2.]])
#tensorB = torch.tensor([[3.,3.,3.],[4.,4.,4.]])
#
## Print the contents of the two tensors
#print("tensorA:", tensorA)
#print("tensorB:", tensorB)

# Vertically concatenate tensorA and tensorB: (default: dim=0)
concat_v = torch.cat((tensorA, tensorB), dim=0)
print("Vertically concatenate tensorA and tensorB: (default: dim=0)")
print(concat_v)


Vertically concatenate tensorA and tensorB: (default: dim=0)
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])


In [18]:
# prompt: Follow the same procedure as before, but with the text,
# "Horizontally concatenate tensorA and tensorB (dim=1)"
# and the variable, concat_h

# Horizontally concatenate tensorA and tensorB (dim=1)
concat_h = torch.cat((tensorA, tensorB), dim=1)
print("Horizontally concatenate tensorA and tensorB (dim=1)")
print(concat_h)


Horizontally concatenate tensorA and tensorB (dim=1)
tensor([[1., 1., 1., 3., 3., 3.],
        [2., 2., 2., 4., 4., 4.]])


Her code was a bit different.

In [20]:
concat_v = torch.cat([tensorA, tensorB])
concat_h = torch.cat([tensorA, tensorB], dim=1)

print(concat_v)
print(concat_h)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])
tensor([[1., 1., 1., 3., 3., 3.],
        [2., 2., 2., 4., 4., 4.]])


The CoPilot generation was fun. I got to learn prompt engineering, especially with the original 2x3 tensors. It did it with only PyTorch methods, but I had to be pretty explicit. Then, I told it that it could pass in arrays.

In [21]:
!date +'%s_%Y-%m-%dT%H:%M:%S%z'

1718947145_2024-06-21T05:19:05+0000
